## import libraries
```{r}
library(tidyverse)
library(ggplot2)
library(lubridate)
```

## import data
```{r}
opportunities_table = as_tibble(read.csv("opportunities_table_v1.csv", header = TRUE))
countries_mapping = as_tibble(read.csv("countries_mapping.csv", header = TRUE))
opportunity_background_required_table = as_tibble(read.csv("opportunity_background_required_table.csv", header = TRUE))
background_mapping = as_tibble(read.csv("background_mapping.csv", header = TRUE))
```

## Data profiling
```{r}
opportunities_table %>% summary
opportunities_table %>% head
```

## Create background ratio table
## Description: To quantify which background the opportunity is leaning towards for prediction.
```{r}
##map the background with a higher level grouping e.g. business, engineering, science, etc...
opportunity_background_required_table_wide <- opportunity_background_required_table %>% left_join(background_mapping, by = "background")

##transform the long format to wide format for further processing
opportunity_background_required_table_wide <- opportunity_background_required_table_wide %>% select(opportunity_id, Type) %>% group_by(opportunity_id,Type) %>% count() %>% spread(Type, n) %>% replace_na(list(Arts = 0, Business = 0, Engineering = 0, Humanity = 0, Other = 0, Politics = 0, Science = 0))
```

## Feature engineering
```{r}
##change date type
opportunities_table$created_at <- as.Date(opportunities_table$created_at)
opportunities_table$applications_close_date <- as.Date(opportunities_table$applications_close_date)
opportunities_table$earliest_start_date <- as.Date(opportunities_table$earliest_start_date)
opportunities_table$latest_end_date <- as.Date(opportunities_table$latest_end_date)
##replace na values with 0 assume no values means no minimum duration requirement
opportunities_table$duration_min <- opportunities_table$duration_min %>% replace_na(0)

##add new features - open_window, flexibility, start_month
# Description
# open_window: The duration which the opportunity is open from creation date to application deadline.
# flexibility: The range which the applicant can engage in the opportunity.
# start_month: Extract the start month from the earliest start date
opportunities_table_new_features <- opportunities_table %>% mutate(created_month = month(month_created), open_window = as.numeric(applications_close_date - created_at), flexibility = as.numeric(latest_end_date - earliest_start_date), start_month = month(earliest_start_date))
```

##filter out outliers
```{r}
opportunities_table_new_features %>% summary
```

```{r}
#replace all NA values with new mean after trimming upper and lower 0.01 outliers for open_window
opportunities_table_new_features$open_window[is.na(opportunities_table_new_features$open_window)] <- opportunities_table_new_features %>% filter(!is.na(open_window)) %>% filter(open_window < quantile(opportunities_table_new_features$open_window, 0.99, na.rm = TRUE)) %>% filter(open_window > quantile(opportunities_table_new_features$open_window, 0.01, na.rm = TRUE)) %>% .$open_window %>% mean

#filter out the upper and lower 0.01 outliers for open_window
opportunities_table_new_features <- opportunities_table_new_features %>% filter(!is.na(open_window)) %>% filter(open_window < quantile(opportunities_table_new_features$open_window, 0.99, na.rm = TRUE)) %>% filter(open_window > quantile(opportunities_table_new_features$open_window, 0.01, na.rm = TRUE))

#filter out the upper 0.01 outliers for openings
opportunities_table_new_features <- opportunities_table_new_features %>% filter(openings < quantile(opportunities_table_new_features$openings, 0.99, na.rm = TRUE))

#filter out start_month NA
opportunities_table_new_features <- opportunities_table_new_features %>% filter(!is.na(start_month))

#replace all NA values with new mean after trimming upper and lower 0.01 outliers for flexibility
opportunities_table_new_features$flexibility[is.na(opportunities_table_new_features$flexibility)] <- opportunities_table_new_features %>% filter(!is.na(flexibility)) %>% filter(flexibility < quantile(opportunities_table_new_features$flexibility, 0.99, na.rm = TRUE)) %>% filter(flexibility > quantile(opportunities_table_new_features$flexibility, 0.01, na.rm = TRUE)) %>% .$flexibility %>% mean

#filter out the upper and lower 0.01 outliers for flexibility
opportunities_table_new_features <- opportunities_table_new_features %>% filter(!is.na(flexibility)) %>% filter(flexibility < quantile(opportunities_table_new_features$flexibility, 0.999, na.rm = TRUE)) %>% filter(flexibility > 0)

#add new mapping for name_entity
countries_mapping$name_entity <- as.character(countries_mapping$name_entity)
countries_mapping$Region <- as.character(countries_mapping$Region)
opportunities_table_new_features <- opportunities_table_new_features %>% left_join(countries_mapping, by = c("name_entity" = "name_entity"))
opportunities_table_new_features <- opportunities_table_new_features %>% filter(!is.na(Region))

#add background weighting
opportunities_table_new_features <- opportunities_table_new_features %>% left_join(opportunity_background_required_table_wide) %>% mutate(Arts = Arts/background_r_count, Business = Business/background_r_count, Engineering = Engineering/background_r_count, Humanity = Humanity/background_r_count, Other = Other/background_r_count, Politics = Politics/background_r_count, Science = Science/background_r_count) %>% replace_na(list(Arts = 0, Business = 0, Engineering = 0, Humanity = 0, Other = 0, Politics = 0, Science = 0))

```

## re-evaluate the data
```{r}
head(opportunities_table_new_features)
summary(opportunities_table_new_features)
opportunities_table_new_features %>% group_by(Region) %>% count
```


```{r}
#output the file
write.csv(opportunities_table_new_features, file = "opportunities_table_for_prediction_v3.csv")
```


